MERGE INTO NAME_TABLE AS OBJ
USING TABLE_NAME AS SRC
	ON obj.ID = SRC.ID
WHEN MATCHED AND OBJ.COLUMN_ > src.COLUMN_
	THEN UPDATE SET OBJ.COLUMN_ = SRC.COLUMN_,
					OBJ.COLUMN_ = SRC.COLUMN_,
					OBJ.COLUMN_ = SRC.COLUMN_
WHEN MATCHED AND OBJ.COLUMN_ < SRC.COLUMN_
	THEN DELETE
WHEN NOT MATCHED BY TARGET
	THEN INSERT VALUES(SRC.COLUMN_, SRC.COLUMN_, SRC.COLUMN_ /*,ETC..*/)
WHEN NOT MATCHED BY SOURCE AND OBJ.COLUM_ > 25 --EXAMPLE
	THEN DELETE
OUTPUT $ACTION AS TheAction, inserted.*, deleted.* 	;